trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*
pr:
  branches:
    include:
    - master
    
variables:
- group: sonarqube
- group: sign
- group: ossrh

resources:
  repositories:
    - repository: templates
      type: github
      name: bakdata/bakdata-project-templates

jobs:
- template: build.yml@templates
- template: create_tag_version.yml@templates
- template: upload_release.yml@templates
- template: upload_snapshot.yml@templates
