trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*
pr:
  branches:
    include:
    - master
    
variables:
- group: sonarqube
- group: sign
- group: ossrh

resources:
  repositories:
    - repository: templates
      type: github
      name: bakdata/bakdata-project-templates
      endpoint: bot

jobs:
- template: azure/build.yml@templates
- template: azure/create_tag_version.yml@templates
- template: azure/upload_release.yml@templates
- template: azure/upload_snapshot.yml@templates
